language: php

php:
  - hhvm
  - 5.5
  - 5.6
  - 7.0
  - 7.1

addons:
  mariadb: '10.0'

before_script:
  # Install mediawiki
  - bash ./build/travis/install-mediawiki.sh
  # Install this lib
  - composer install

script:
  - composer lint
  - composer sniff
  - nohup php -S 0.0.0.0:8080 -t ./../web > /dev/null 2>&1 &
  - until curl -s localhost:8080; do true; done > /dev/null
  - composer phpunit-coverage

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover $TRAVIS_BUILD_DIR/coverage.clover

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  irc:
    channels:
      - "chat.freenode.net##add"
    on_success: change
    on_failure: always
